# ç½‘é¡µæ ·å¼
mode: auto
banner:
  enable: true
  title: é“‚å±‘çš„è®°å½•ç‚¹
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
bg_image:
  enable: true
  url: /images/bg.jpg
  # dark:
  opacity: 0.8
fireworks:
  enable: true
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'
cursor:
  enable: true
footer:
  since: 2022
  icon:
    name: carbon:chemistry
    animated: true
    color: '#0078E7'
    url: /about/
    title: é“‚å±‘
  powered:
    enable: false
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²ä¸Šå·¥
    suffix: ï¼ˆï¼›Â´Ğ´ï½€ï¼‰ã‚
    start_time: '2022-07-23T04:57:57'
favicon: /favicon.ico


# ä¾§è¾¹æ 
avatar:
  url: /images/face.jpg
  status:
    enable: true
    emoji: ğŸ’˜
    message: å–œæ¬¢ä½ å“¦
pages:
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: ri:hearts-line
    color: hotpink
menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: ri:clipboard-line
social:
  - name: GitHub
    link: https://github.com/boxie123
    icon: ri:github-line
    color: '#6e5494'
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/35192025
    icon: ri:bilibili-line
    color: '#FF8EB3'
  - name: E-Mail
    link: mailto:platinum0shard@gmail.com
    icon: ri:mail-line
    color: '#8E71C1'
  - name: æ·»åŠ QQå¥½å‹
    link: tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=1824390830&website=www.oicqzone.com
    icon: ri:qq-line
    color: '#12B7F5'


# è¯„è®ºç³»ç»Ÿ
# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: boxie123/boxie123.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: dark
comment:
  enable: true
  candidates:
    - waline
  tips:
    - â†“â†“â†“è·³è½¬issueså’Œdiscussionsè¯„è®ºï¼Œå›å¤æ›´åŠæ—¶å“¦â†“â†“â†“
waline:
  enable: true
  serverURL: https://hexo-1v0nhftyo-boxie123.vercel.app/
  visitor: true
  comment: true
  emoji:
    # - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    # - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    # - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: [nick]
github_issues:
  enable: true
  username: boxie123
  repository: boxie123.github.io
  filters: is:issue
github_discussions:
  enable: true
  username: boxie123
  repository: boxie123.github.io


# æœç´¢ç³»ç»Ÿ
search:
  modal: true
engine_search:
  enable: false
# search
# https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true


# æ–‡ç« æ ·å¼
post_edit:
  enable: true
  url: https://github.com/boxie123/boxie123.github.io/tree/hexo/source/
reward:
  enable: true
  icon: ri:hand-heart-line
  color: '#FF8EB3'
  # url: https://space.bilibili.com/1485569
  comment: ä»€ä¹ˆï¼Ÿä½ è¦è¯·æˆ‘å–å¥¶èŒ¶ï¼Ÿãƒ¾(â€¢Ï‰â€¢`)o
  methods:
    - name: bilibili
      path: /images/aigeface.jpg
      link: https://www.bilibili.com/v/pay/charge/?upmid=35192025&upurl=%2F%2Fspace.bilibili.com%2F35192025&upname=Pt_ion&upavatar=https%3A%2F%2Fi0.hdslb.com%2Fbfs%2Fface%2F1074c8b414bb03de2e4c8f9724ab23dfed3f3c2c.webp&oid=35192025&otype=up&from=space_index
      color: darkred
      icon: ri:battery-saver-line
    - name: çˆ±å‘ç”µ
      path: /images/aigeface2.jpg
      link: https://ifdian.net/a/pt_ion
      color: gold
      icon: ri:user-add-line
wordcount:
  enable: true
  count: true
  time: true
codeblock:
  copy_btn: true


# å…¶ä»–é¡µé¢
albums:
  enable: true
girls:
  enable: true
tags:
  è‰¾é¸½: hotpink
  å­¦ä¹ : saddlebrown
  æ•™ç¨‹: royalblue
  ç¬”è®°: gold
  åˆ†äº«: '#0078e7'
  éšç¬”: mediumpurple
  hexo: sienna
  åŒ–å­¦: cyan
  Python: mediumblue
wordcloud:
  enable: false
categories:
  é“‚å±‘çš„éšæ‰‹è®°å½•: '#FB7299'
  åç«¯ç¼–ç¨‹: mediumorchid 
  é¡µé¢å¼€å‘: lime
  å°ç©å…·: navy


# é™„åŠ åŠŸèƒ½
baidu_push: true

mourn:
  enable: true
  days:
    - 4-4
    - 7-7
    - 9-18