mode: auto

banner:
  enable: true
  title: é“‚å±‘çš„è®°å½•ç‚¹
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

bg_image:
  enable: true
  url: https://boxie123-1305125924.cos.ap-beijing.myqcloud.com/images/bg.jpg
  # dark:
  opacity: 0.8

reward:
  enable: true
  icon: ri:hand-heart-line
  color: '#FF8EB3'
  # url: https://space.bilibili.com/1485569
  comment: ç»™å¯çˆ±çš„é¸½å®ä¸€ç‚¹æ”¯æŒå§ãƒ¾(â€¢Ï‰â€¢`)o
  methods:
    - name: å…³æ³¨ï¼
      path: https://boxie123-1305125924.cos.ap-beijing.myqcloud.com/images/aigeface.jpg
      link: https://space.bilibili.com/1485569
      color: darkred
      icon: ri:user-add-line
    - name: å……ç”µï¼
      path: https://boxie123-1305125924.cos.ap-beijing.myqcloud.com/images/aigeface2.jpg
      link: https://www.bilibili.com/v/pay/charge?upmid=1485569&upurl=%2F%2Fspace.bilibili.com%2F1485569&upname=%E8%89%BE%E9%B8%BD%E6%B3%B0%E5%B0%94%E5%BE%B7&upavatar=http%3A%2F%2Fi2.hdslb.com%2Fbfs%2Fface%2Fc86cec17c8343a4b7a5f7e2d29447a9ba521a5be.jpg&oid=1485569&otype=up&from=zone
      color: gold
      icon: ri:battery-saver-line

fireworks:
  enable: true
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'

avatar:
  url: https://boxie123-1305125924.cos.ap-beijing.myqcloud.com/images/face.jpg
  status:
    enable: true
    emoji: ğŸ’˜
    message: å–œæ¬¢ä½ å“¦

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: boxie123/boxie123.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: dark

search:
  modal: true

engine_search:
  enable: false

# search
# https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true

post_edit:
  enable: true
  url: https://github.com/boxie123/boxie123.github.io/tree/hexo/source/

albums:
  enable: true

girls:
  enable: true

tags:
  è‰¾é¸½: hotpink
  å­¦ä¹ : saddlebrown
  æ•™ç¨‹: royalblue
  ç¬”è®°: gold
  åˆ†äº«: '#0078e7'
  éšç¬”: mediumpurple
  hexo: sienna
  åŒ–å­¦: cyan

categories:
  é“‚å±‘çš„éšæ‰‹è®°å½•: '#FB7299'
  é¡µé¢å¼€å‘: lime
  å°ç©å…·: navy

pages:
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: ri:hearts-line
    color: hotpink

menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: ri:clipboard-line

wordcloud:
  enable: false

cursor:
  enable: true

baidu_push: true

# cdn:
#   pre: https://cdn.jsdelivr.net/gh/boxie123/boxie123.github.io@latest

comment:
  enable: true
  candidates:
    - waline
  tips:
    - è‹¥æ‚¨æƒ³åŠæ—¶å¾—åˆ°å›å¤æé†’ï¼Œå»ºè®®è·³è½¬ GitHub Issues è¯„è®ºã€‚
    - æ¬¢è¿ç›´æ¥åŠ æˆ‘QQå¥½å‹å“¦

waline:
  enable: true
  serverURL: https://hexo-1v0nhftyo-boxie123.vercel.app/
  visitor: true
  comment: true
  emoji:
    # - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    # - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    # - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: [nick]

github_issues:
  enable: true
  username: boxie123
  repository: boxie123.github.io
  filters: is:issue

github_discussions:
  enable: true
  username: boxie123
  repository: boxie123.github.io

social:
  - name: GitHub
    link: https://github.com/boxie123
    icon: ri:github-line
    color: '#6e5494'
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/35192025
    icon: ri:bilibili-line
    color: '#FF8EB3'
  - name: E-Mail
    link: mailto:platinum0shard@gmail.com
    icon: ri:mail-line
    color: '#8E71C1'
  - name: æ·»åŠ QQå¥½å‹
    link: tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=1824390830&website=www.oicqzone.com
    icon: ri:qq-line
    color: '#12B7F5'

footer:
  since: 2022
  icon:
    name: carbon:chemistry
    animated: true
    color: '#0078E7'
    url: https://boxie123.github.io/about/
    title: é“‚å±‘
  powered:
    enable: false
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²ä¸Šå·¥
    suffix: ï¼ˆï¼›Â´Ğ´ï½€ï¼‰ã‚
    start_time: '2022-07-23T04:57:57'

mourn:
  enable: true
  days:
    - 4-4
    - 7-7
    - 9-18

codeblock:
  copy_btn: true

wordcount:
  enable: true
  count: true
  time: true