mode: auto

banner:
  enable: true
  title: é“‚å±‘çš„è®°å½•ç‚¹
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

reward:
  enable: false

fireworks:
  enable: true
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'

avatar:
  url: /images/face.jpg
  status:
    enable: true
    emoji: ğŸ’˜
    message: å–œæ¬¢ä½ å“¦

github_issues:
  enable: false

github_discussions:
  enable: false

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: boxie123/boxie123.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: dark

engine_search:
  enable: false

# search
# https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true

post_edit:
  enable: true
  url: https://github.com/boxie123/boxie123.github.io/tree/hexo/source/

albums:
  enable: true

girls:
  enable: true

tags:
  è‰¾é¸½: pink
  å­¦ä¹ : saddlebrown
  æ•™ç¨‹: royalblue
  ç¬”è®°: dimgray
  åˆ†äº«: '#0078e7'
  éšç¬”: mediumpurple

categories:
  äº‘æ¸¸çš„å°è§†é¢‘: '#FB7299'

pages:
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: ri:women-line
    color: hotpink

menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: ri:clipboard-line

wordcloud:
  enable: true

cursor:
  enable: true

baidu_push: true

cdn:
  pre: https://cdn.jsdelivr.net/gh/boxie123/boxie123.github.io@latest

comment:
  enable: true
  tips:
    - è‹¥æ‚¨æƒ³åŠæ—¶å¾—åˆ°å›å¤æé†’ï¼Œå»ºè®®è·³è½¬ GitHub Issues è¯„è®ºã€‚
    - è‹¥æ²¡æœ‰æœ¬æ–‡ Issueï¼Œæ‚¨å¯ä»¥ä½¿ç”¨ Comment æ¨¡ç‰ˆæ–°å»ºã€‚
  github_issues:
    enable: true
    username: boxie123
    repository: boxie123.github.io
    filters: is:issue

  github_discussions:
    enable: true
    username: boxie123
    repository: boxie123.github.io

social:
  - name: GitHub
    link: https://github.com/boxie123
    icon: ri:github-line
    color: '#6e5494'
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/35192025
    icon: ri:bilibili-line
    color: '#FF8EB3'
  - name: E-Mail
    link: mailto:platinum0shard@gmail.com
    icon: ri:mail-line
    color: '#8E71C1'
